### ISSUE TITLE
Wechat QR code is outdated

### ISSUE THREAD

**Issue by senseab** [AOSC-Dev/newsroom#2]
see coffee-break/20230922/imgs/wechat.png

**Comment by MingcongBai** [comment]
Unfortunately the QR codes expire every 7 days. Here's an updated QR code.

![IMG_2985](https://github.com/AOSC-Dev/newsroom/assets/5006263/9f331030-4c3a-4c81-976a-cae07880d639)

**Comment by senseab** [comment]
okay, remove that qrcode may be better?

**Comment by MingcongBai** [comment]
> okay, remove that qrcode may be better?

Well, we'd still need to post it somewhere. But maybe we can figure out a way to let people get their own QR code.

I'll close this issue for now since it's beyond our control. Feel free to follow up here with further questions.
